tasks:
  - init: npm install
    command: npm run storybook

vscode:
  extensions:
    - esbenp.prettier-vscode@5.1.3:t532ajsImUSrA9N8Bd7jQw==
    - dbaeumer.vscode-eslint@2.1.3:1NRvj3UKNTNwmYjptmUmIw==
    - runem.lit-plugin@1.1.10:/yk3Arh4MIQ3RwIcHwbX3Q==

ports:
  - port: 6006
    onOpen: open-preview
